# Generated by Django 4.0.1 on 2022-01-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Leader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Leader.leader')),
            ],
        ),
    ]
